x-build:
  &build
  context: ./
  args:
    PHP_VERSION: ${PHP_VERSION-7.0}
    COMPOSER_VERSION: ${COMPOSER_VERSION-2.2}
  dockerfile: docker/Dockerfile

services:
  setup:
    image: registry.xaer.de/xaer/php:${PHP_VERSION-7.0}-cli
    build:
      <<: *build
      target: php
    volumes:
      - ./:/src
      - ../secrets:/secrets
    working_dir: "/src"
    secrets:
      - source: composer_auth
        target: /root/.composer/auth.json
    command: ["sh", "-c", "composer update"]
  php:
    image: registry.xaer.de/xaer/php:${PHP_VERSION-7.0}-cli
    build:
      <<: *build
      target: php
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - ./:/src
      - ../secrets:/secrets
    working_dir: "/src"
secrets:
  composer_auth:
    file: ./auth.json
