name: PHP CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests:
    name: PHP Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: PHP_VERSION=${{ matrix.php-version }} docker-compose run php composer test-ci
